"""remove email table

Revision ID: d7f4277fdbd2
Revises: c0121785e69f
Create Date: 2025-07-29 16:03:15.643312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7f4277fdbd2'
down_revision: Union[str, Sequence[str], None] = 'c0121785e69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='departments')
    op.drop_column('departments', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('email'), 'departments', ['email'], unique=True)
    # ### end Alembic commands ###
